# docker-compose up
# ssh admin@84.201.178.78
services:
  web:
    build: .
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
    env_file:
      - .env
  db:
    image: postgres:16.0
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis
    container_name: 'redis_app'
    volumes:
      - ./redis_data:/data
    env_file:
      - .env
    depends_on:
      - db
  celery:
    build: .
    container_name: 'celery_app'
    command: celery --app=celery worker --loglevel=info
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
volumes:
  postgres_data:
  static_volume:
  redis_volume: