version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0:0:0:0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8001:8000"
    expose:
      - "5432"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  static_volume: