version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0:0:0:0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - "8001:8000"
    expose:
      - "5432"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16.0
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser" ]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: redis
    restart: always
    container_name: 'affectionate_bhaskara'
    command: redis-server
    ports:
      - '6379:6379'
  celery:
    build: .
    container_name: 'inspiring_galileo'
    command: celery -A core worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
volumes:
  postgres_data:
  static_volume: