# Generated by Django 5.1.6 on 2025-02-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='kurs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.kurs', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание курса', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название курса', null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='preview',
            field=models.ImageField(blank=True, help_text='Укажите превью(изображение)', null=True, upload_to='media/', verbose_name='Изображение(превью)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(blank=True, help_text='Введите название урока', null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='preview',
            field=models.ImageField(blank=True, help_text='Укажите превью(изображение)', null=True, upload_to='media/', verbose_name='Изображение(превью)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(blank=True, help_text='Добавьте ссылку на видео урока', null=True, verbose_name='Ссылка на видео'),
        ),
    ]
