# Generated by Django 5.1.6 on 2025-02-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="pays",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="session_id",
            field=models.CharField(blank=True, null=True, verbose_name="ID сессии"),
        ),
    ]
