# Generated by Django 4.2.19 on 2025-03-04 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_pays_link_pays_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pays",
            name="way_to_pay",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Наличные", "наличные"),
                    ("Перевод на счёт", "перевод на счёт"),
                ],
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
